version: '3'
services:
  meli-morse-app:
    container_name: meli-morse-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: on-failure
    volumes:
      - meli-morse:/usr/src/app/
    networks:
      - meli-morse

volumes:
  meli-morse:
networks:
  meli-morse:
    driver: bridge